name: Checkout Proof

on:
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest

    steps:
      - name: Current folder path and list its contents
        run: |
          echo "Current folder path: $(pwd)"
          echo "Contents of the current folder:"
          ls -la

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: List of contents
        run: |
          echo "Contents of the repository after checkout:"
          ls -la

      - name: Counts how many files are now present
        run: |
          file_count=$(ls -1 | wc -l)
          echo "Number of files in the repository after checkout: $file_count"

      - name: Print completion message
      
